language: node_js
node_js:
- "0.10"

before_script:
- npm install -g  balderdashy/sails appdevdesigns/appdev-cli#develop
- cd /tmp
- /home/travis/build/appdevdesigns/opstool-mpdReport/test/setup/install.sh
- cd ad-test/node_modules
- mv /home/travis/build/appdevdesigns/opstool-mpdReport .
- cd opstool-mpdReport
- npm install mocha chai mocha-phantomjs phantomjs
- npm install

script:
- npm test
 
